### ISSUE TITLE
Question: Invariant learning

### ISSUE THREAD

**Issue by KatCe** [zilongwang123/LeaVe#1]
Hello,
I read your great paper and was curious to understand the invariant learning part better, so I tried the example you mention in the README: After setting the contract srcObservation to [] (or including only the uncommented statement with id ADD), the verification fails as expected. However, no invariants were learned, except one for the clock. Is this expected too?

I got the following output:

```...
   Begin the 16th loop...
	The invariant for verification is:
	- { id: clk, cond: 1, attrs: [ { value: clk, width: 1 } ]}

	 Checking the inductive step...
	The inductive step is satisfied!
	The invariant learned is:
	- { id: clk, cond: 1, attrs: [ { value: clk, width: 1 } ]}


	Time for base step: 1
	Time for inductive step: 33

3. Check the satisfaction based on learned strongest attacker.

	The CPU is VULNERABLE under the attack w.r.t the contract!!
```

------

With the contract regarding with id MUL, I got the following result:

```
	... Checking the inductive step...
	The inductive step is satisfied!
	The invariant learned is:
	- { id: clk, cond: 1, attrs: [ { value: clk, width: 1 } ]}
	- { id: decode, cond: 1, attrs: [ { value: decode, width: 1 } ]}
	- { id: decode_reg, cond: 1, attrs: [ { value: decode_reg, width: 1 } ]}
	- { id: mul_imm, cond: 1, attrs: [ { value: mul_imm, width: 24 } ]}
	- { id: mul_rd, cond: 1, attrs: [ { value: mul_rd, width: 32 } ]}
	- { id: mult, cond: 1, attrs: [ { value: mult, width: 1 } ]}
	- { id: nxpc, cond: 1, attrs: [ { value: nxpc, width: 32 } ]}
	- { id: nxpc2, cond: 1, attrs: [ { value: nxpc2, width: 32 } ]}
	- { id: nxpc3, cond: 1, attrs: [ { value: nxpc3, width: 32 } ]}
	- { id: pc, cond: 1, attrs: [ { value: pc, width: 32 } ]}
	- { id: rd_old, cond: 1, attrs: [ { value: rd_old, width: 32 } ]}
	- { id: ready, cond: 1, attrs: [ { value: ready, width: 1 } ]}
	- { id: register_old, cond: 1, attrs: [ { value: register_old, width: 32 } ]}
	- { id: retire, cond: 1, attrs: [ { value: retire, width: 1 } ]}
	- { id: retire_wire, cond: 1, attrs: [ { value: retire_wire, width: 1 } ]}
	- { id: wb_we, cond: 1, attrs: [ { value: wb_we, width: 1 } ]}
	- { id: Retire, cond: 1, attrs: [ { value: retire, width: 1 } ]}

	Time for base step: 1
	Time for inductive step: 75

3. Check the satisfaction based on learned strongest attacker.

	Verification passed!!
```

What is the meaning of these invariants? I assumed I could use these as srcObservation and would get a pass result, however, the verification failed and again only outputted the invariant regarding the clock.  Am I misunderstanding the output?

Could you please elaborate on these results? 

How does LeaVe learn an invariant like the MUL example in srcObservations?

Thank you very much!

**Comment by zilongwang123** [comment]
1. If you start with the empty contract for RE, yes, only the 'clk' will be learned.
2. With the contract MUL, the set of invariants learned is kind of "equivalent" to the contract, but not equivalent. So if the contract observations are always the same, then the invariants learned are always the same. But from invariants, we cannot reach the contract, it's one way. This also answers why the verification failed if you use these invariants as contract.
3. The contract equivalence is only checked on retirement. So the invariants can not be interpreted as a contract.

**Comment by KatCe** [comment]
Hello @zilongwang123 . Thank you very much for your quick and detailed response.
